on:
  push:
    branches: 
      - build

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 18 # Use Node.js 18 here

      - name: Install dependencies
        run: npm install --force

      - name: Build site
        run: npm run build:prod

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.TOKEN }}
          publish_dir: ./build # Change this if your build output directory is different
